# Generated by Django 5.2.7 on 2025-10-11 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_short_sm', models.ImageField(upload_to='themes/logo_short_sm/')),
                ('logo_short_lg', models.ImageField(upload_to='themes/logo_short_lg/')),
                ('logo_long_sm', models.ImageField(upload_to='themes/logo_long_sm/')),
                ('logo_long_lg', models.ImageField(upload_to='themes/logo_long_lg/')),
                ('logo_square_sm', models.ImageField(upload_to='themes/logo_square_sm/')),
                ('logo_square_lg', models.ImageField(upload_to='themes/logo_square_lg/')),
                ('logo_circle_sm', models.ImageField(upload_to='themes/logo_circle_sm/')),
                ('logo_circle_lg', models.ImageField(upload_to='themes/logo_circle_lg/')),
                ('primary_gradient_color_1', models.CharField(default='blue', max_length=32)),
                ('primary_gradient_color_2', models.CharField(default='grape', max_length=32)),
                ('gradient_degree', models.IntegerField(default=142)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('default_border_radius', models.IntegerField(default=8)),
                ('default_shadow', models.CharField(max_length=100)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
