# Generated by Django 5.2.7 on 2025-10-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenanttheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenanttheme',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_theme', to='tenants.tenant'),
        ),
    ]
